### ISSUE TITLE
Translation from GRPC errors in interceptor

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/go-utils#29]
@htdvisser you removed coversion from/to GRPC errors in d9c49f0, is there a reason for this? Current implementation does not do aforementioned conversion(https://github.com/TheThingsNetwork/go-utils/blob/8622223277037145f4ed2beda936a39e6382a14d/grpc/rpclog/grpc.go).
This change broke error type detection in NOC clients(cc @romeovs , errors returned by NOC now are probably all of `unknown` type) Are we planning to integrate it back?

**Comment by htdvisser** [comment]
Yes, we are planning on returning it

**Comment by htdvisser** [comment]
Resolved by #35
